### ISSUE TITLE
Spatial filter vector

### ISSUE THREAD

**Issue by VladislavAksiotis** [bioelectric-interfaces/nfb_studio#11]
It could be better, firstly, to rename "Matrix path" inside the spatial filter block to "Vector path" or something similar and, secondly, to separate the two functions - adding a path to a txt file with a vector and typing the vector right inside the box. Because right now you could type to "Matrix path" either the vector or the path, but new users will not be aware of this.

**Comment by andreasxp** [comment]
Implemented in master.
