### ISSUE TITLE
Statistics type inside a block

### ISSUE THREAD

**Issue by VladislavAksiotis** [bioelectric-interfaces/nfb_studio#12]
Inside a block, there is the box "Update statistics". If checked, it should allow choosing the statistics type below, but right now you can choose the type with any state of "Update". It is misleading for users since it is always open for changes.

![image](https://user-images.githubusercontent.com/60115817/114983312-230a6200-9e99-11eb-8361-90511584a557.png)

**Comment by andreasxp** [comment]
Fixed in master
