### ISSUE TITLE
Default values when importing xml

### ISSUE THREAD

**Issue by VladislavAksiotis** [bioelectric-interfaces/nfb_studio#5]
After exporting the xml file the following blocks change their values, so reopening this xml gives your different experiment settings:
fFFTWindowSize (500 became 1000)
sTemporalFilterType (cfir changes to butter)
sTemporalSmootherType (savgol to exp)
sTemporalType is always identity (even if there is an envelop detection block at the end)

Maybe, there are more default values that I used in my settings and don't know that they could change

**Comment by andreasxp** [comment]
Can you make me an XML file with all the buggy values?
Put as much complicated stuff in it as possible, so every part of import-export engine is tested.
I will put it in as an integration test, so that we can be sure going forward that nothing breaks.

**Comment by VladislavAksiotis** [comment]
> Can you make me an XML file with all the buggy values?
> Put as much complicated stuff in it as possible, so every part of import-export engine is tested.
> I will put it in as an integration test, so that we can be sure going forward that nothing breaks.

Ok, I will try every changeable block and sent an extended xml

**Comment by VladislavAksiotis** [comment]
I tried to change every part (I hope) of mutable properties and found nothing new except the previous findings.

It is a signal created in Studio. Nothing else (outside the signal) was changed.
```
	<vSignals>
		<DerivedSignal>
			<sSignalName>fz</sSignalName>
			<fSmoothingFactor>0.4</fSmoothingFactor>
			<method>Hilbert Transform</method>
			<sTemporalSmootherType>savgol</sTemporalSmootherType>
			<fBandpassLowHz>8.0</fBandpassLowHz>
			<fBandpassHighHz>12.0</fBandpassHighHz>
			<fFFTWindowSize>600.0</fFFTWindowSize>
			<sTemporalFilterType>cfir</sTemporalFilterType>
			<fTemporalFilterButterOrder>2</fTemporalFilterButterOrder>
			<SpatialFilterMatrix>Fz=1</SpatialFilterMatrix>
			<sTemporalType>identity</sTemporalType>
		</DerivedSignal>
```

It is the signal after importing.
```
	<vSignals>
		<DerivedSignal>
			<sSignalName>fz</sSignalName>
			<fSmoothingFactor>0.4</fSmoothingFactor>
			<method>Hilbert Transform</method>
			<sTemporalSmootherType>exp</sTemporalSmootherType>
			<fBandpassLowHz>8.0</fBandpassLowHz>
			<fBandpassHighHz>12.0</fBandpassHighHz>
			<fFFTWindowSize>1000.0</fFFTWindowSize>
			<sTemporalFilterType>butter</sTemporalFilterType>
			<fTemporalFilterButterOrder>2</fTemporalFilterButterOrder>
			<SpatialFilterMatrix>Fz=1</SpatialFilterMatrix>
			<sTemporalType>identity</sTemporalType>
		</DerivedSignal>
```

If you need a specific xml file for an integration test I will create it, but what should it contain? Only rows with buggy values or a completed pipeline?

**Comment by andreasxp** [comment]
Fixed in master
