### ISSUE TITLE
Choosing an LSL from a file

### ISSUE THREAD

**Issue by VladislavAksiotis** [bioelectric-interfaces/nfb_studio#8]
NFB lab has the option to choose (browse) an LSL file in another window with folder search, while in Studio you should type the full path. It will be great if such function will be added.

**Comment by andreasxp** [comment]
Remind me - what field are we talking about?

**Comment by VladislavAksiotis** [comment]
![lsl](https://user-images.githubusercontent.com/60115817/112180778-e8503980-8c0c-11eb-8754-de4cb8b63306.jpg)

Maybe, it will be useful to add the "Browse" button here

**Comment by andreasxp** [comment]
Thanks for the suggestion! Implemented this in master.
